### PR TITLE
Add benchmarks on real world datasets

### PR DESCRIPTION
**Pull request by mfelsche**
Those datasets are the same as used in the [java RoaringBitmap](https://github.com/RoaringBitmap/RoaringBitmap/tree/master/real-roaring-dataset/src/main/resources/real-roaring-dataset)

Now we only need to add comparable benchmarks.

Benchmarks are run by doing:

```
ROARING_DATASET=census-income make bench
```

It is possible to run the same benchmarks on different datasets by varying the environment variable.

### CODE REVIEW

**Comment by rhagenson** [comment]
Looks good to me. Is there a straightforward way to run all benchmarks?

**Comment by mfelsche** [comment]
Good point! I made it run the benchmarks on all datasets if no `ROARING_DATASET` env var has been provided (which can be a list of multiple ones, separated by comma).

**Comment by rhagenson** [comment]
Great update and glad the linter is happy now. I will take another look immediately after work today to see how the new "run all" default works. 

@salty-blue-mango do you have any comments on this before it is merged to main?

**Review by rhagenson — APPROVED** [review]
Looks good to me. I pulled the changes local and had no issues. Is there a "formal" way these benchmarks are typically shown to compare across implementations of roaring that we should include?

**Comment by mfelsche** [comment]
@rhagenson Currently, with ponybench there is no way to format the output differently, we'd need to do this in a post processing step. I think I will tackle comparability to one of the other roaring implementations in a follow up PR.

**Pull request merged**
